build:
  version: "2.0"


loans:
  message: "Welcome to EazyBank loans related QA APIs"
  contactDetails:
    name: "Samatha - QA Lead"
    email: "samatha@gmail.com"
  onCallSupport:
    - (666)555-1234
    - (666)555-1235