build:
  version: "3.0"


loans:
  message: "Welcome to EazyBank loans related local APIs"
  contactDetails:
    name: "Xuyang - Developer"
    email: "xuyang@gmail.com"
  onCallSupport:
    - (555)555-1234
    - (555)555-1235