build:
  version: "1.0"


loans:
  message: "Welcome to EazyBank loans related prod APIs"
  contactDetails:
    name: "Samatha - Product Owner"
    email: "samatha@gmail.com"
  onCallSupport:
    - (777)555-1234
    - (777)555-1235